---
- name: Setup EC2 Instance for Yii2 Application
  hosts: ec2
  become: yes
  vars:
    app_domain: yii2-app.example.com
    docker_stack_name: yii2app
    docker_image: username/yii2-app:latest
    github_repo: https://github.com/username/yii2-docker-swarm.git
    nginx_conf_path: /etc/nginx/conf.d
    app_repo_path: /opt/yii2-docker-swarm

  tasks:
    # Update system packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Install Docker and dependencies
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    # Setup Docker Swarm
    - name: Check if Swarm is initialized
      shell: docker info | grep -i 'swarm: active'
      register: swarm_status
      ignore_errors: yes
      changed_when: false

    - name: Initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: swarm_status.rc != 0

    # Install and Configure NGINX
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Create NGINX conf directory
      file:
        path: "{{ nginx_conf_path }}"
        state: directory
        mode: '0755'

    - name: Copy NGINX configuration
      template:
        src: templates/yii2-app.conf.j2
        dest: "{{ nginx_conf_path }}/{{ app_domain }}.conf"
        mode: '0644'
      notify: Restart NGINX

    - name: Install Git
      apt:
        name: git
        state: present

    # Clone application repository
    - name: Create app directory
      file:
        path: "{{ app_repo_path }}"
        state: directory
        mode: '0755'

    - name: Clone app repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_repo_path }}"
        version: main

    # Deploy application with Docker Swarm
    - name: Deploy application to Docker Swarm
      shell: |
        cd {{ app_repo_path }}
        docker stack deploy -c docker-compose.yml {{ docker_stack_name }}
      changed_when: true

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
